# gitops-safe/argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: humor-game-monitor
  namespace: argocd
spec:
  project: humor-game-safe
  source:
    repoURL: https://github.com/ShivamSoni1995/Homelab
    targetRevision: main
    path: gitops-safe1/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: humor-game